version: '3.7'
services:
  # client:
  #     build:
  #         context: ./frontend
  #         dockerfile: Dockerfile
  #     tty: true
  #     ports:
  #       - "3000:3000"
  #     volumes: 
  #       - ./frontend:/app
  #       - /app/node_modules
  #     networks:
  #       - frontend
  db:
    image: mysql:5.7
    ports:
       - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password!
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - backend
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py run
    ports:
      - "5000:5000"
    environment:
      MYSQL_USER: "sourcesageuser"
      MYSQL_PASSWORD: "password!"
      MYSQL_DB: "sourcesagedb"
    volumes:
      - appdata:/var/www/
    depends_on: 
      - db
    networks:
      # - frontend
      - backend

networks:
  # frontend:
  #   driver: bridge
  backend:
    driver: bridge
volumes:
  mysqldata:
    driver: local
  appdata:
    driver: local
