"""create products-variants-images table

Revision ID: 159b5c968188
Revises: 2a76aeba34c9
Create Date: 2020-10-25 16:59:17.355663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '159b5c968188'
down_revision = '2a76aeba34c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_images', 'image_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('product_images', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('product_images_ibfk_1', 'product_images', type_='foreignkey')
    op.drop_constraint('product_images_ibfk_2', 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key('product_images_ibfk_2', 'product_images', 'products', ['product_id'], ['id'])
    op.create_foreign_key('product_images_ibfk_1', 'product_images', 'images', ['image_id'], ['id'])
    op.alter_column('product_images', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('product_images', 'image_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
